### ISSUE TITLE
JSON Parse Error: SyntaxError: Unexpected end of input

### ISSUE THREAD

**Issue by aprasad1993** [jpillora/node-edit-google-spreadsheet#29]
I am getting this error after google login and spreadsheet searching has been done. Please help me out. 

app.get('/lead', function(req, res){

	console.log(req.query.fullname);

Spreadsheet.load({
    debug: true,
    spreadsheetId: '*********',
    worksheetName: 'Sheet1',
    // Choose from 1 of the 3 authentication methods:
    //    1. Username and Password
    username: 'aprasad1993@gmail.com',
    password: '********',
    // OR 2. OAuth
    // oauth : {
    //   email: 'my-name@google.email.com',
    //   keyFile: 'my-private-key.pem'
    // },
    // // OR 3. Token
    // accessToken : {
    //   type: 'Bearer',
    //   token: 'my-generated-token'
    // }
  }, function sheetReady(err, spreadsheet) {
    if(err) throw err;

    spreadsheet.add({ 3: { 5: "Anurag Prasad" } });

    spreadsheet.send(function(err) {
      if(err) throw err;
      console.log("Updated Cell at row 3, column 5 to 'hello!'");
    });

  });
});

**Comment by jpillora** [comment]
should have no more JSON issues now we're using `xml2json` to parse all responses
