### ISSUE TITLE
Getting specific entry from rows

### ISSUE THREAD

**Issue by orangeFlavor95** [jpillora/node-edit-google-spreadsheet#31]
I was wondering how do you get an specific spreadsheet value from the rows object? And could we modify that element of the rows object? Is the rows object an array? Could we modify an entry by setting rows[int][int]="value"? I'm really a noob student trying to finish a project and do not have much node.js experience.

**Comment by jpillora** [comment]
Sorry for the late response. Have a look at the `examples/` directory and then get them working and then look at the docs.
