### ISSUE TITLE
Google Documents List API is being deprecated | Migrate to Drive

### ISSUE THREAD

**Issue by NickCis** [jpillora/node-edit-google-spreadsheet#55]
Warning: The deprecation period for Version 3 of the Google Documents List API is nearly at an end. 
    On April 20, 2015, we will discontinue service for this API. This means that service calls to the API are 
    no longer supported, and features implemented using this API will not function after April 20, 2015. 
    You must migrate to the Drive API as soon as possible to avoid disruptions to your application.

[source](https://developers.google.com/google-apps/documents-list/)

Posible solution: [migrate to drive](https://developers.google.com/drive/)

**Comment by jpillora** [comment]
Thanks for the warning will definitely get to this before the cut off date

**Comment by jpillora** [comment]
I just remembered why I mentioned the doc-list API in the README - I was going to add a feature to create spreadsheets, though it was bigger than I thought it would be and fell far behind the stable branch. I think I'll just make to decision now to wipe it as this module should only deal with the spreadsheets API and that's it. If people want to create spreadsheets they can use the [google-drive](https://github.com/niftylettuce/node-google-drive) module. Thanks for the heads up though

**Comment by NickCis** [comment]
I'm currently not using it to create spreadsheets, only to edit existing ones, will i be affected by this issue?.

Thanks for the fasts answers!

**Comment by jpillora** [comment]
You won't, all will work as normal

**Comment by NickCis** [comment]
Thanks!
