### ISSUE TITLE
=concatenate(S2,T2,U2) instead of actual value

### ISSUE THREAD

**Issue by przemyslawpluta** [jpillora/node-edit-google-spreadsheet#62]
After getting the spreadsheet from google instead of getting the actual text visible in the cell I'm getting the action that is used to produce its content. Is there a way to receive just the text?

```
{ '1': 1,
     '2': 'name',
     '3': '=CONCATENATE("new item ",B2," & ",C2)',
     '4': 00000012,
     '5': '=CONCATENATE(A2,"_",G2,"_",H2,"_",I2,"_",J2)',
     '6': 1,
     '7': '=concatenate(S2,T2,U2)',
     ...
}
``

**Comment by jpillora** [comment]
There is, it's [abit hidden](https://github.com/jpillora/node-edit-google-spreadsheet#spreadsheetreceive-options-callback-err--rows--info--) though.

``` js
spreadsheet.receive({getValues: true}, callback( err , rows , info ) ) {
  //...
});
```

**Comment by przemyslawpluta** [comment]
Thanks.
