### ISSUE TITLE
preserve empty cells

### ISSUE THREAD

**Issue by przemyslawpluta** [jpillora/node-edit-google-spreadsheet#63]
When `rows` get returned empty cells from spreadsheet are discarded. Is there a way to preserve them? As you can see below we're missing cell `3`. Thanks again.

```
'5':
   { '1': 3,
     '2': 'tag',
     '4': 'new item',
     '6': 'test',
     '7': 'Long name',
     '8': 'index',
     '9': 'try command',
     ...
```

**Comment by jpillora** [comment]
The Google API only returns the filled cells. So I'm not actually removing them. You could get around this by copying the columns object into a columns array:

``` js
var row = result["5"];
var cols = [];
for(var k in row)
  cols[k] = row[k];

for(var i = 1; i < cols.length; i++)
  console.log(i, cols[i]);
```
And you should see `3 undefined` (note: I haven't actually this code)

**Comment by przemyslawpluta** [comment]
@jpillora Thanks.
