### ISSUE TITLE
Error installing npm

### ISSUE THREAD

**Issue by samperlmutter** [jpillora/node-edit-google-spreadsheet#65]
When I try to install the npm with `npm install edit-google-spreadsheet` in my root directory I get [this error](http://puu.sh/gwmyk/faaaf1d1ac.PNG). I am using Windows 8.1 and Atom to write the code.Has anyone else had this problem and found a solution?

**Comment by sey** [comment]
The error message tells you what you need to do. You are missing the `python`executable. So you need to download [Python](https://www.python.org/downloads/windows/) if you don't have it already. Then you install it and set the PYTHON variable to the path of the Python.exe file. 
Next time, please use [Google](https://www.google.fr/search?q=can%27t+find+python+executable). The first link is a [Stackoverflow](http://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies) post with the exact same error back in 2013. On the Internet, you are [almost](http://www.explainxkcd.com/wiki/index.php/979:_Wisdom_of_the_Ancients) never alone ;-).

**Comment by jpillora** [comment]
Thanks @sey
