### ISSUE TITLE
Add method, columns and rows from variable. 

### ISSUE THREAD

**Issue by aleixo** [jpillora/node-edit-google-spreadsheet#84]
Hello. First of all. Great work, but i ended up spending to many time on this due to one probably mine issue that i ask you to help me. 

First time with node. I managed to write to the google sheet, but i want to append data. I want to say to the method that it will write let´s say, variable x that stores the col, variable y that stores the row like this spreadsheet.add{x:{y:"test"}}

Thank you very much.

**Comment by jpillora** [comment]
Checkout https://github.com/jpillora/node-edit-google-spreadsheet#faq

**Comment by aleixo** [comment]
Hello

Thank you for the quick reply but that was no help. I already checked out all the documentation, even the spreadsheet.add method. Bu i can not do this... Help please.  I really need to sleep.

**Comment by aleixo** [comment]
Can you give one usage example of using one array as parameter for the add method?

**Comment by jpillora** [comment]
think you might need to wrap it in another array: [[1,2,3,4]] haven't used
this project or node in nearly 2 years now

**Comment by MPWhite** [comment]
Was this issue ever resolved? I'm running into the same issue

**Comment by bogdy29** [comment]
+1

**Comment by jpillora** [comment]
```
cols = {};
cols[y] = 42;
rows = {};
rows[x] = cols;
spreadsheet.add(rows);
```
?

**Comment by bogdy29** [comment]
The question was: how to add a new row every time you run the spreadsheet.add ?

there is this lastRow information, so normally should work if you add information to lastRow+1,
but how you do that ?

in spreadsheet.receive you have the info.lastRow, but how to use it to add a new line ?

I have this example: 

function sheetReady(err, spreadsheet) {
        
        if(err) throw err;

        spreadsheet.receive(function(err, rows, info) {
          if(err) throw err;

           console.log("Found rows:", info.lastRow);

        });

        spreadsheet.add({ info.lastRow + 1 : { 5: "hello!" } });

        spreadsheet.send(function(err) {
          if(err) throw err;
        });

    }

so lastRow is showing ok in the console, but in the spreadsheet.add I don't have the lastRow+1.

**Comment by jpillora** [comment]
* If you need `lastRaw`, then you'll need to `add` inside the callback from `receive`
* JavaScript (ES5) doesn't allow `{ info.lastRow + 1 : { 5: "hello!" } }`, instead you have to build the object first, then pass it to `add`.
* You'll probably want to use `send`'s `autoSize` option to resize the spreadsheet once you go past the bottom (see `send` docs)

**Comment by bogdy29** [comment]
Thanks for the reply.

is clear now, I just need to figure out how to build the object first, before pass it to add...I guess this
is the problem that others also didn't figure it out.

**Comment by bogdy29** [comment]
can you provide an example or give us a hint, how to build this object first ?

then I can create an example file and put in in examples folder, etc...with a pull request of course. Then
this issue can be fixed->closed I guess.

thanks a lot!

**Comment by bogdy29** [comment]
I managed to have an example to work :)

is not the best, but this is it:

function sheetReady(err, spreadsheet) {
        
        if(err) throw err;

        spreadsheet.receive(function(err, rows, info) {
          if(err) throw err;

           var nextLastRow = info.lastRow + 1;
           var addData = '{' + '"' + nextLastRow + '"' + ': { "5" : "test" } }';

           spreadsheet.add(JSON.parse(addData));

           spreadsheet.send(function(err) {
              if(err) throw err;
           });

        });

    }

**Comment by jpillora** [comment]
yeah, that'd work, you can also:

```js
var addData = {};
addData[nextLastRow] = { "5" : "test" };
spreadsheet.add(addData);
```
