### ISSUE TITLE
Segmentation fault with Node 4.0.0

### ISSUE THREAD

**Issue by gruberb** [jpillora/node-edit-google-spreadsheet#86]
Hey, I'm getting a  segmentation fault error when executing the translation-creator.js.

Any help/bugfix?

**Comment by TimJohns** [comment]
Hello @gruberb - I did a quick check with 4.0.0, and was able to add rows to a sheet with no seg fault.  Can you add a stack trace and/or other repro steps that might help us narrow this down a bit?

**Comment by gruberb** [comment]
Sorry, It solved itself. I had to remove my `node_modules` folder, and run `npm install` and `npm rebuild` again after the update to 4.0.0
