### ISSUE TITLE
Google OAuth Error: Error: failed to obtain an authentication token, request failed with HTTP code 401: invalid_client

### ISSUE THREAD

**Issue by cloakedninjas** [jpillora/node-edit-google-spreadsheet#93]
Getting this with an old(ish) project. Updated to latest npm version but no change. And I'm using a PEM key.

Any ideas?

**Comment by cloakedninjas** [comment]
Ok, found the problem. It's caused by trying to use `OAuth` authentication. Looks like Google have now deprecated this.

Switching to `OAuth2`, fixed it for me.

**NB:** Remember to copy `get_oauth2_permission.js` into your working directory and then execute it to get a `refresh_token`.

**Comment by JawadQamar** [comment]
how to get copy of get_oauth2_permission.js ??
